/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wztnxdvtqdcepmjyoihs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dG54ZHZ0cWRjZXBtanlvaWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3OTY4NDMsImV4cCI6MjA3NjM3Mjg0M30.-Bo1tvA4frZH3kxkJCoqhn7Yw-ismP2-uS7fA1-6fmg"